# -*- coding: utf-8 -*-
"""CajeroAutomatico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fG1NLyFtTolaQEVnSacL1quzTgK52Lg7
"""

#Ejercicio python cajero automático

def cajeroAutomatico(saldoDisponible):
  print('\n************Bienvenido a tu cajero automático MOHW***********\n')
  print('¿Qué quieres realizar?\n')
  print('1. Retirar')
  print('2 Depositar')
  print('3 Consulta de saldo')
  print('4 Salir\n')

  opcion=int(input('Selecciona la opción que quieras realizar: '))

  if opcion==1:
    retiro=float(input('¿Cuanto quieres retirar?: '))
    if retiro>saldoDisponible:
      print('\nLo siento, no tienes esa cantidad de dinero')
      return cajeroAutomatico(saldoDisponible)
    saldoDisponible=saldoDisponible-retiro
    respuesta=(f'\nHas retirado ${retiro} MXN, tu saldo disponible actualizado es de ${saldoDisponible} MXN')
    print(respuesta)
    return cajeroAutomatico(saldoDisponible)

  if opcion==2:
    deposito=float(input('¿Cuanto quieres depositar?: '))
    saldoDisponible=saldoDisponible+deposito
    respuesta=f'\nDeposito completado, tu saldo actualizado es de ${saldoDisponible} MXN'
    print(respuesta)
    return cajeroAutomatico(saldoDisponible)

  if opcion==3:
    respuesta=f'\nTu saldo es de {saldoDisponible} MXN\n'
    print(respuesta)
    return cajeroAutomatico(saldoDisponible)

  if opcion==4:
    print('\nGracias por utilizar nuestros servicios, buen día :)\n')

  else:
    print('\nOpción no disponible\n')
    return cajeroAutomatico(saldoDisponible)

saldo=float(input('Este es un simulador, ¿Con cuanto dinero ficticio quieres comenzar?: '))

cajeroAutomatico(saldo)