# -*- coding: utf-8 -*-
"""PhythonBásico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fUB0x5Od6QNbtHwgwR08HrVNt8fbPWZ4
"""

##Variables: Almacenan información de manera temporal (Cualquier tipo de dato)

miVariable="Hola mundo"
print(miVariable)
miVariable=15
print(miVariable)
#No es necesario indicar el tipo de variable que voy a utilizar.
#Se pueden cambiar el valor de las varibables
#Las variables se almacenan en una dirección de memoria RAM

x=10
y=2
z=x+y
print(x)
print(y)
print(z)
print(id(x)) #Dirección de memoria RAM donde está almacendo el valor de 'x'

#EJERCICO DE VARIABLES
nombre="José Olmedo"
telefono='5512345678'
mail="josomedo@mail.com"
print(nombre)
print(telefono)
print(mail)

#TIPOS DE DATOS EN PYTHON
#Numericos: Interger, Complex number, float
#Dictonary
#Boolean
#Set
#Sequence Type: Strings, List, Tuple

x=10
y="Hola a todos"
z=10.5
w=True
print(type(x)) #Nos dice el tipo de dato de una variable
print(type(y))
print(type(z))
print(type(w))

#MANEJO DE CADENAS
miGrupoFavorito="Aerosmith"
comentario="(la mejor banda de rock)"
#Concatenación
print("Mi grupo favorito es: " + miGrupoFavorito +" "+ comentario)
print("Mi grupo favorito es:", miGrupoFavorito, comentario) #Nótese que no hay espacio entre los dos puntos
print("Mi grupo favorito es:", miGrupoFavorito +" "+ comentario)

#Conversión de tipo de dato
numero1="1"
numero2="2"
print("Suma:",int(numero1)+int(numero2))

#Tipos bool (bolean)
miVariable=False
print(miVariable)

miVariable=1<2
print(miVariable)

if miVariable is False:  #is actúa como "es"
  print("El resultado fue falso")
else:
  print("El resultado fue verdero")

#Procesar la entrada de usuario (función input)
#La función input regresa una CADENA
resultado=input("Por favor ingresa algo: ")
print("Lo que ingresaste es:", resultado)

#Continuación....
numero1=float(input("Ingresa el primer número: "))
numero2=float(input("Ingresa el segundo número: "))
print("La suma de ambos números es:",numero1+numero2)

#Ejercicio "Califica tu día"
calificacion=int(input("¿Cómo estuvo tu día? (1 al 10): "))
print("Tu día estuvo de: "+str(calificacion))

#Ejercicio "Datos del libro"
titulo=input("Proprcione el título del libro: ")
autor=input("Proporcione el autor del libro: ")
print(titulo,"fue escrito por",autor)

#OPERADORES ARITMÉTICOS
#Suma: +
#Resta: -
#Multiplicación: *
#División: /
#División de tipo entero: //
#Exponenciación: **
#Módulo: %
operandoA=float(input("Ingresa un número: "))
operandoB=float(input("Ingresa otro número: "))

suma=operandoA+operandoB
resta=operandoA-operandoB
multiplicacion=operandoA*operandoB
division=operandoA/operandoB
divisionEntera=operandoA//operandoB
exponenciacion=operandoA**operandoB
modulo=operandoA%operandoB

print(f'El resultado de la suma es: {suma} unidades')#Nueva forma de imprimir información
print(f'El resultado de la resta es: {resta} unidades')
print(f'El resultado de la multipliacion es: {multiplicacion} unidades')
print(f'El resultado de la división es: {division} unidades')
print(f'El resultado de la división entera es: {divisionEntera} unidades')  #Nótese que se trunca
print(f'El resultado de la exponenciacion es: {exponenciacion} unidades')
print(f'El resultado del módulo es: {modulo} unidades')

#Ejercicio propuesto
#Calcular el área y perímetro de un rectángulo
"""Las triples comillas
te permiten
agregar comentarios de multiples
lineas"""
print("Programa para calcular el área y perimetro de un rectángulo")
alto=float(input("Ingresa el alto: "))
ancho=float(input("Ingresa el ancho: "))
area=alto*ancho
perimetro=alto+ancho
print(f'El área del rectángulo es de: {area} unidades cuadradas')
print(f'El perímetro del rectángulo es de: {perimetro} unidades')

#Ejercicio número par o impar
numero=int(input("Ingrese un número: "))
numero=numero%2
if numero==0:
  print("El número que ingresaste es par")
else:
  print("El número que ingresaste es impar")

#Ejercicio determinar si eres mayor de a
edad=int(input("Ingresa tu edad porfavor: "))
if edad>=18:
  print("Eres mayor de edad, puedes pasar")
else:
  print("No eres mayor de edad, no puedes pasar")

#OPERADORES LÓGICOS
"""
and: Devuelve True si ambos operandos son True
or: Devuelve True si alguno de los operandos es True
not: Devuelve True si alguno de los operandos es False (invierte valor: not a)
"""
a=False
b=True
resultado=not a
print(resultado)

#Ejercicio valor dentro de rango (and)
"""
Pedir valor y decir se encuentra dentro del rango de 0 al 5 """
valor=float(input("Ingrese un valor: "))
if valor>=0 and valor<=5:
  print(f'El valor {valor} se encuentra dentro del rango de 0 a 5')
else:
  print(f'El valor {valor} no se encuentra dentro del rango de 0 a 5')

#Ejercicio operador or
"""Asistir al juego del hijo"""
vacaciones=input("¿Estás de vacaciones? (Ingrese S/N): ")
descanso=input("Es un día de descanso (Ingrese S/N): ")
#Validación
if vacaciones=='S':
  vacaciones=True
else:
  vaciones=False
if descanso=='S':
  descanso=True
else:
  descanso==False
#Uso de 'or'
if vacaciones or descanso:
  print("Puedes asistir al juego de tu hijo")
else:
  print("No puedes asistir al juego de tu hijo")

#Ahora con operador not
if not(vacaciones or descanso):
  print("No puedes asistir al juego de tu hijo")
else:
  print("Puedes asistir al juego de tu hijo")

#Otro ejercicio usando operadores lógicos
"""Rango dentro de 20 ó 30 años"""
edad=int(input("Ingresa tu edad: "))
if edad>=20 and edad<=30:
  print("Estas dentro del rango de 20 a 30")
else:
  print("No estás dentro del rango de 20 a 30")

#Ejercicio mayor de dos números
numero1=float(input("Ingresa el primer número: "))
numero2=float(input("Ingresa el segundo número: "))
if numero1<numero2:
  print(f'El número mayor es: {numero2}')
elif numero1>numero2:
  print(f'El número mayor es: {numero1}')
else:
  print(f'El número {numero1} es exactamente igual al {numero2}')

"""Realice un progrma que pida los siguientes datos
de un libro:
Nombre
ID
Precio
Indicar si el envío es gratuito
y lo imprima en pantalla
"""
nombre=input("Ingrese el nombre del libro: ")
ID=input("Ingrese el ID del libro: ")
precio=float(input("Ingrese el precio del libro (MXN): "))
envio=input("¿El libro cuenta con envío gratuito? (S/N): ")
print(f'Nombre: {nombre}')
print(f'Precio: {precio}')
print(f'ID: {ID}')
if envio=='S':
  print('¿Envío gratuito?: Sí')
else:
  print('¿Envío gratuito?: No')

#Ejercico estación del año según el mes
mes=int(input("Ingresa el mes del año en el que estamos (1-12): "))
if mes==1 or mes==2 or mes==12:
  print("Estamos en invierno")
elif mes==3 or mes==4 or mes==5:
  print("Estamos en primavera")
elif mes==6 or mes==7 or mes==8:
  print("Estamos en verano")
elif mes==9 or mes==10 or mes==11:
  print("Estamos en otoño")
else:
  print("No ingresaste un mes valido")

#Ejercicio etapas de la vida
edad=int(input("Ingresa tu edad: "))
if edad>=0 and edad<=10:
  print("La infancia es increible")
elif edad>10 and edad<=20:
  print("Muchos cambios y mucho estudio")
elif edad>20 and edad<=30:
  print("Amor y comienza el trabajo")
elif edad>30:
  print("Eres un hombre maduro")
else:
  print("Ingresaste una edad no válida")

#Ejercicio sistema de calificaciones
"""
Crear sistema de calificaciones, ingresar valor entre 0 y 10
Si está entre 9 y 10: A
Si está entre 8 y menor a 9: B
Si está entre 7 y menor a 8: C
Si está entre 6 y menor a 7: D
Si está entre 0 y menor a 6: F
Cualquier otro valor debe imprimir: Valor incorrecto
Ejemplo:
Ingresa tu califcación: 8.5
Tu nota es: B
"""
##############################################
calificacion=float(input("Ingresa tu calificación: "))
if calificacion==10 and calificacion>=9:
  print("Tu nota es: A")
elif calificacion<9 and calificacion>=8:
  print("Tu nota es: B")
elif calificacion<8 and calificacion>=7:
  print("Tu nota es: C")
elif calificacion<7 and calificacion>=6:
  print("Tu nota es: D")
elif calificacion<6:
  print("Tu nota es: F")
else:
  print("Valor incorrecto")

#Ciclo While
"""Mientras una condición sea 'True' se ejecutará indefinidamente
Si se cambia durante el ciclo a 'False', se terminará el ciclo
"""
ciclo=True
contador=0
while ciclo:
  contador=contador+1
  if contador==10:
    ciclo=False
  print(contador)

#Ejercicio While descendente
ciclo=True
contador=5
print(contador)
while ciclo:
  contador=contador-1
  if contador==0:
    ciclo=False
  print(contador)

#Ciclo For en python

"""Este programa recorre cada letra en la cadena"""
cadena="Hola"
contador=0
for letra in cadena:
  contador+=1
  print(contador)

#Palabra break interrumpe el ciclo
for letra in "Holanda":
  if letra=='a':
    print(f'Letra encontrada: {letra}')
    break
  else:
    print('Letra aún no encontrada')

#Palabra continue

#Listas siempre se definen entre corchetes: perros=[]
nombres=['José', 'Marco', 'Isaac', 'Angélica', 'Mike','Wilson','Ron','Han','Paulie']
#Acceder a algun elemento es con el índice
print(nombres[0])
print(nombres[1])
print(nombres[2])
print(nombres[3])
print("")
print("Ahora de manera inversa:")
print("")
#Acceder a los elementos de manera inversa
print(nombres[-1])
print(nombres[-2])
print(nombres[-3])
print(nombres[-4])

#Acceder a un rango de valores de una lista
print(nombres[0:4]) #Accede desde el índice 0 hasta el 3 sin tocar el 4

#Del inicio de la lista hasta un índice sin tocarlo
print(nombres[:5])

#Del índice hasta el final de la lista
print(nombres[2:])

#Cambiar un valor de la lista
nombres[0]='Angel'
print(nombres[0])

#Recorrer una lista
i=0
for nombre in nombres:
  print(f"Este es el nombre número {i} de la lista: {nombre}")
  i+=1

#Pedir el largo de una lista
Largo=len(nombres)
print(Largo,'\n')

#Agregar elemento a una lista:

nombres.append('Mariano')
nombres.append('Gato')
print(nombres, "\n")


#Insertar elementos en un índice específico
nombres.insert(4, 'Robbie')
print(nombres, '\n')

#Eliminar elementos de una lista por valor
nombres.remove('Gato')
print(nombres, '\n')

#Eliminar el ultimo elemento (Aquí se elimina 'Feo)
nombres.append('Feo')
nombres.pop()
print(nombres, '\n')

#Eliminar elemento por indice
nombres.append('Tonto')
del nombres[-1]
print(nombres, '\n')

#Limpiar lista
nombres.clear()
print(nombres, '\n')

#Borrar lista por completo
del nombres
#print(nombres)

#Ejercicios de rango
'''Sintaxis de range(inicio<opcional>, fin<obligatorio>, incremento<opcional>)'''
#Ejercicio 1: Iterar en un rango de 0 a 10 e imprimir numeros divisibles entre 3
for i in range(0,11,1):
  if i%3==0:
    print(f"El número {i} es divisible entre 3")
#Ejercicio 2: Crear un rango de números de 4 al 122 e imprimirlos con paso de 5 en 5
print("")
for i in range(4,122,5):
  print(i)

#TUPLAS son muy parecidas a las listas pero son de caracter inmutable
animales=('Perro', 'Gato', 'Tigre', 'Oso', 'Leopardo', 'Pericos', 'Guacamayas')
print(animales, '\n')

#Longitud de una tupla
print(len(animales), '\n')

#Acedder a un elemento en particular
print(animales[1], '\n')

#Recorrer una tupla
for animal in animales:
  print(animal, end=', ')  #El end indica como queremos que se imprima el siguiente elemento, por defecto es '\n'
print('\n')

#Acceder a un rango de valores
print(animales[2:5])

#De tupla a lista
ListaAnimales=list(animales)
print(ListaAnimales, '\n')

#De lista a tupla
TuplaAnimales=tuple(ListaAnimales)
print(TuplaAnimales)

#Ejercicios de tuplas
''' Dada la siguiente tupla crear una lista de números menores a 5 '''
MiTupla=(13,1,8,3,2,5,8)

MiLista=[]
for numeros in MiTupla:
  if numeros<5:
    MiLista.append(numeros)
print(MiLista)

#Set no tiene un orden, no permite almacenar elementos duplicados, tampoco es posible modificarlos pero si es posible agregar más elementos

planetas={'Mecurio', 'Venus', 'Tierra', 'Marte', 'Júpiter', 'Saturno', 'Urano', 'Neptuno','Plutón'}
print(planetas, '\n')

#Largo
print(len(planetas), '\n')

#Revisar si un elemento está presente
print('Tierra' in planetas, '\n')

#Añadir elementos
planetas.add('Wilsonio')
print(planetas, '\n')

#Eliminar elementos
planetas.remove('Wilsonio')
print(planetas, '\n')

#Limpiar set
planetas.clear()
print(planetas, '\n')

#Borrar set
del planetas

#DICCIONARIOS
'''Tienen una estructura de llave:valor'''
diccionario={
    'IDE': 'Integrated Development Environment',
    'OOP': 'Object Oriented Programming',
    'API': 'Application Programming Interface',
    'BD': 'Base de Datos',
    'HTML': 'HyperText Markup Language',
    'CSS': 'Cascading Style Sheets',
    'DBMS': 'Database Management System',
    'SQL': 'Structured Query Language',
    'JS': 'JavaScript',
}
print(diccionario, '\n')

#Largo
print(len(diccionario), '\n')

#Acceder a un elemento por clave
print(diccionario['IDE'], '\n')
#Otra forma
print(diccionario.get('DBMS'), '\n')

#Modificar elementos
diccionario['IDE']='integrated development environment'
print(diccionario, '\n')

#Agregar elementos
diccionario['Py']='Python'

print(diccionario, '\n')

#Eliminar elementos
del diccionario['OOP']
diccionario.pop('API')
print(diccionario, '\n')

#Recorrer un diccionario
for clave,valor in diccionario.items():
  print(clave,': ',valor)

print('')

#Solo llaves
for clave in diccionario.keys():
  print(clave, end=', ')

print('')

#Solo valores
for valor in diccionario.values():
  print(valor, end=', ')

print('\n')

#Verificar si hay algun elemento
print('IDE' in diccionario)

#Limpiar diccionario
diccionario.clear()
print('\n', diccionario, '\n')

#Borrar diccionario
del diccionario

#Funciones en Python

#Crear una función
def miFuncion():
  print('Hola')

miFuncion()

#Argunemntos en una función
def Saludar(nombre,apellido):
  print(f'Hola {nombre} {apellido}')

#Primero=input('Ingresa tu nombre: ')
#Segundo=input('Ingresa tu apellido: ')
print('')
Saludar('Primero','Segundo')

def suma(a=2,b=7):
  return a+b

#Sin argumentos
print('')
print(suma())
#Con argumentos
print('')
print(suma(5,3))

#Funciones las cuales no sabemos cuantos argumentos queremos pasar
def listarNombres(*nombres): #De manera interna esto va a ser una tupla
  for nombre in nombres:
    print(f'Hola {nombre}', end=', ')
  print('\n')

listarNombres('José','Marco','Isaac','Angélica','Mike','Ron','Han','Wilson','Paulie','Robbie','Mariano')

'''Ejercicio de funciones: Creaar una función que sume n números'''

def sumarNumeros(*numeros):
  resultado=0
  for numero in numeros:
    resultado=numero+resultado
  return(f'La suma de los números que ingresaste es: {resultado}')

sumarNumeros(5,2,33,40)
#Video 77

#Funciones que acepten como argumentos diccionarios
def ListarTerminos(**kwargs): #Así acepta elementos clave valor
  for llave,valor in kwargs.items():
    print(f'{llave}:{valor}')

ListarTerminos(IDE='Integrated Development Environment', HTML='Hipertext Markup Language', SQL='Structured Query Language')

#def funcionTodaRara(nombre, *args, **kwargs):

def desplegarNombres(nombres):
  for nombre in nombres:
    print(nombre)

nombres=['Pepe','Marco','Isaac\n']
desplegarNombres(nombres)
desplegarNombres('Carlos')